version: '3'
services:
    judge-server:
        image: registry.cn-shanghai.aliyuncs.com/aliyun_hzcool/judger-server
        restart: always
        read_only: true
        container_name: judge-server
        tmpfs:
            - /tmp
        environment: 
            - GOPATH=/
            - SERVICE_PORT=:8001
            - ACCESS_TOKEN=123
        volumes: 
            - /home/hzcool/go/src/myGinProject/media:/src/test_case
            - /home/hzcool/go/src/myGinProject/data/log:/src/log
            - /home/hzcool/go/src/myGinProject/data/tmp:/src/tmp
        ports: 
            - 8000:8001
